# Generated by Django 5.1.5 on 2025-01-28 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='data',
        ),
    ]
