# Generated by Django 5.1.5 on 2025-01-29 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_uploadedfile_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='summary_text',
            field=models.TextField(default='No summary available'),
        ),
    ]
