# Generated by Django 5.1.5 on 2025-01-30 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_uploadedfile_client_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadlink',
            name='requirement_message',
            field=models.TextField(default=''),
        ),
    ]
