# Generated by Django 5.1.5 on 2025-01-30 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_uploadlink_requirement_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadlink',
            name='requirement_message',
            field=models.TextField(default=' '),
        ),
    ]
