# Generated by Django 5.1.5 on 2025-02-01 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
