# Generated by Django 5.1.5 on 2025-02-05 21:10

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_client_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='file',
            field=models.FileField(upload_to=api.models.file_upload_path),
        ),
    ]
