# Generated by Django 5.1.5 on 2025-02-06 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_uploadedfile_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='role',
            field=models.CharField(default=''),
        ),
    ]
